### PR TITLE
[EAQS] Better Archery Tombstone compatibility

### PR DESCRIPTION
**Pull request by jsza**
This prevents items being placed into Better Archery's two hidden inventory rows when taking items from resized tombstones.

Really feels terribly hacky and fragile, but it works... Good enough for now?

### CODE REVIEW

**Comment by jsza** [comment]
FYI, I haven't tested this in combination with any other inventory modification mods.

**Comment by jsza** [comment]
This may not actually fit so well in EAQS itself? I've contacted the author about the relevant changes; for now I'm thinking to move these patches into a standalone plugin if that's alright.

**Comment by RandyKnapp** [comment]
I'm fine with that. I'd prefer not to have specific other mod code in the base mods.

**Comment by jsza** [comment]
Just released this @ https://www.nexusmods.com/valheim/mods/1221/

Pretty sure a good chunk of item loss bug reports on EAQS are from this interaction; maybe worth pointing out somewhere? Also is it okay if reply to some recent posts on the EAQS asking them to try this out?

**Comment by RandyKnapp** [comment]
Yeah, I'm going to pull in all your PR's today, and get a release out. I'll
link to this mod too

**Comment by jsza** [comment]
Huzzah 🎉 

Just a heads-up: it looks like NexusMods EAQS 2.0.7 release has 2.0.6 DLL (unless it's some caching issue on my end).

**Comment by RandyKnapp** [comment]
No you're right, something went wrong on my end

**Pull request closed without merging**
