### PR TITLE
Change rarity weight for tools

### PR DESCRIPTION
**Pull request by Ou1Law**
All tools must have the same rarity weight - they are tools, not weapons

### CODE REVIEW

**Comment by RandyKnapp** [comment]
Why do you think this change should happen? Could you explain more, please?

**Comment by Ou1Law** [comment]
Bcs with the old values it is practically impossible to get a hammer or a hoe more "magic", although these tools are used until of the endgame. Tools will still not drop out ahead of time, but now they will seem to be in the same group of "tools" and have the same chances of becoming magic. rare, epic or legendary.

**Comment by RandyKnapp** [comment]
So my intention was this:
A) you might get lucky in the early game with a magic or rare hammer
B) For late game tools, you should be enchanting the ones you want, not relying on drops

I don't think I'm going to pull this change in, but thank you for the suggestion.

**Comment by Ou1Law** [comment]
Perhaps, then, it is worth taking the same average value for all instruments? [ 80, 16, 4, 0 ]
It just isn't fair that we can get the legendary pickaxe but we can't get the hoe.

**Comment by RandyKnapp** [comment]
It's a config for a reason, you're free to modify it as you see fit for
your own purposes and enjoyment! 😊

**Pull request closed without merging**
