### PR TITLE
Anye77 localization

### PR DESCRIPTION
**Pull request by anye77**
HI RandyKnapp I localized all the translations，
In the translation of the document In the translation  the document of Don't work
  "mod_epicloot_magic": "Magic",
  "mod_epicloot_rare": "Rare",
  "mod_epicloot_epic": "Epic",
  "mod_epicloot_legendary": "Legendary",

Below is a location that I cannot translate and need your help
QQ截图20210730003632

The following is the Chinese document I translated for your release
[translations(Chinese).zip](https://github.com/RandyKnapp/ValheimMods/files/6902140/translations.Chinese.zip)

### CODE REVIEW

**Comment by RandyKnapp** [comment]
Hello, I will set those up as soon as I merge this pull request and have reviewed it

**Comment by RandyKnapp** [comment]
Some of these localization IDs might change. They should be all lowercase with underscores, and you've put some uppercase letters in yours. Just letting you know.

**Comment by anye77** [comment]
I tested it in the game and found no problems

**Comment by RandyKnapp** [comment]
Yes, and I thank you for doing so. However, the reason I want them to all be lowercase is more about keeping consistency with the standard set by the Valheim devs.

**Comment by anye77** [comment]
Thank you for your reminding. When modifying the test, there was no error, but it was ignored

**Comment by anye77** [comment]
EpicLoot.cs Can this file be localized?

Only when compiling DLL files

**Review by RandyKnapp — APPROVED** [review]

**Comment by RandyKnapp** [comment]
I've cleaned this up and committed it.

For the Magic, Rare, Epic, and Legendary labels, they can be modified in the config file. So what I've done is set the default value to the localization ID instead of the English word. That way, new installs will get the localized string. For you, just reset that config value to the default and it should work fine now.

**Pull request merged**
