### PR TITLE
WIP: Implement syncing known items and recipes between clients and server.

### LINKED ISSUE #150: [EpicLoot] Conflict with ServersideSimulations - MustHaveCrafted and MustKnowRecipe
ServersideSimulations (of which I'm an author) allows dedicated servers to create and own objects. As EpicLoot [disables item gating](https://github.com/RandyKnapp/ValheimMods/blob/main/EpicLoot/GatedItemType/GatedItemTypeHelper.cs#L51) when `Player.m_localPlayer == null`, `MustHaveCrafted` and `MustKnowRecipe` configuration ceases to function on the dedicated server.

I wrote a patch to facilitate syncing all players' known materials and recipes to the server [here](https://github.com/jsza/ServersideSimulations_EpicLootPatch). Basically it modifies gated item drops to be aware of all players' progress.

Would this make sense to add to EpicLoot itself? I'd be happy to repurpose this as a PR; maybe you have some thoughts?

(and thanks for the mod! it's been lots of fun)

### PR DESCRIPTION
**Pull request by jsza**
Make CheckIfItemNeedsGate aware of all peers' known items/recipes.

Fixes #150

### CODE REVIEW

**Comment by jsza** [comment]
This is pretty much done, I think, barring some flaw in the approach. I've only been able to test solo on a local dedicated server, so it could use some more eyes on it.

**Review by RandyKnapp — APPROVED** [review]

**Comment by jsza** [comment]
On it.

**Comment by jsza** [comment]
@RandyKnapp Do you have any more info about this? I'm having trouble reproducing.

**Comment by RandyKnapp** [comment]
Got the report from @blaxxun-boop. Blaxxun, can you help provide more context?

**Comment by jsza** [comment]
@blaxxun-boop Very strange. Thought empty known items / recipes lists might trigger the exception, but I can't seem to reproduce it on a fresh character. Thanks for the info though, will have to come back to this tomorrow.

**Comment by jsza** [comment]
Sorry, only coming back to this now. @blaxxun-boop Could I ask what (if any) other plugins you were running at the time? Still no luck reproducing it.

**Comment by blaxxun-boop** [comment]
@jsza Digging a little bit further, this seems like it could be a conflict with [ServerSideMap](https://www.nexusmods.com/valheim/mods/88)

**Pull request merged**
