### PR TITLE
Lifesteal effect

### PR DESCRIPTION
**Pull request by nanonull**
Added Life steal effect to game.
Added debug command to spawn item with desired effect: EpicLoot.Console_Patch.SpawnMagicItemWithEffect

This is the result of new command: **mieffect LifeSteal Club**
image

---
life steal **Flat vs Percentage** value
I'd go with **percentage** as it scales well with player progression
For example:
- starting weapon deals ~25 damage >> 5% lifesteal will heal for ~1 HP on hit when player has ~25-50 total HP. 
So heal ratio is 1/25 - 1/50 of total HP

- in the mid-end game player can deal ~40-100 damage >> 5% lifesteal will heal for ~2-5 HP on hit when player has ~80-150 total HP.
So heal ratio is 1/40 and 1/30 at boundaries.

There are also more splash-damage and damage-over-time in mid+ game - need to check:
- if it is possible to detect that damage and use in life stealing;
- test Life steal is not OP with splash(AoE) damage

--- 
Tests/TODO:

--- 
Done 1) Sword (Legendary 4.2% lifesteal) mieffect LifeSteal SwordSilver
47 damage = 2 HP heal
image

--- 
Done - 1b) Sword (2 targets) 28 + 27 damage = 1.2 + 1.14 HP heal

--- 
Done 1c) add some healing queue so "heal" labels are not popup at the same time when do a lot of AoE damage - consolidate healing requests into bigger one. Currently there are 2 "heal" labels at the same position: 
image

Now heal requests are consolidated:
image

--- 
Tested 2) Stagbreaker (Legendary 5% lifesteal): mieffect LifeSteal SledgeStagbreaker

--- 
Tested (3) Bow - mieffect LifeSteal BowHuntsman

--- 
Ok? (6) hit seagull - neither Humanoid nor Character - it can't be lifesteal target

--- 
Tested (7) hit troll - he is humanoid too :) - can be lifesteal target

--- 
Ok? (8) hit stone golem - he can't be lifesteal target

--- 
Ok? (8) hit skeleton - he can be lifesteal target

--- 
To test (9) hit another player in PvP - lifesteal should work
I assume this should work coz Humanoid.OnDamaged is called from Player.OnDamaged as base.OnDamaged()

--- 
Done (set lifesteal to 3% on Leg.) (10) test lifesteal on swamp  - it should not out-heal generic poison when player constantly hitting one target with IronSword - it should heal for not more than 60-75% of total poison damage.
So when player constantly hitting 2 targets in one hit he should heal for 110-120% of total poison damage

player can do ~25 hits in 16 seconds with AVG damage ~50 (~30 damage per hit, ~90 crit)
25hits * 50 = 1250 damage in 16 seconds on single target
4% of 1250 damage = 50 HP
So player with legendary Lifesteal Iron sword can life-steal 50 HP in 16 seconds in ideal conditions

Leach-poison:  
Poison damage: 50.27679 ttl:16.85509 hits:16 dmg perhit:3.142299 
50 poison damage is 4% of 1250 total damage from Iron sword.

So player can out-heal Leach poison only in ideal conditions: if _constantly hitting someone without pauses_ what is not rly possible coz: stamina limit, enemies can end, player has to parry/dodge regular attacks

Blob-poison: 70 damage in 19 seconds
Player can outheal only 50 HP in 16 seconds = ~80% in ideal conditions

Bonemass:
main poke poison 90 dmg in 20 seconds
Player can outheal ~75% in ideal conditions

--- 
Done (4) Torch - do not allow this effect on torches (and tools) due to insignificant value

--- 
Done (5) set enemy on fire using Fireplace and switch to weapon with lifesteal - test for no crashes

--- 
Obsolete 11) fix tooltip name 

---
Ok 12) Damage over time (fire effect) is not source of lifeStealing 

Tested 13) can lifeSteal from Deer

### CODE REVIEW

**Comment by RandyKnapp** [comment]
Looking good so far. I was going to make that console command eventually :)

**Comment by nanonull** [comment]
Hey @RandyKnapp 
It seams this one ready for review :) There is a checklist with tests you may find above.
Open points (from checklist):

Ok? (6) hit seagull - neither Humanoid nor Character - it can't be lifesteal target 
Ok? (8) hit stone golem - he can't be lifesteal target
Ok? (8) hit skeleton - he **can be** lifesteal target - I think this is fine and you?
Todo 11) fix tooltip name - I am not sure how to fix this UI thing, need help

**Comment by SirFrostingham** [comment]
This looks awesome! Thanks for the great work everyone! Mad thanks to @RandyKnapp for the mod!

**Comment by nanonull** [comment]
Still can't find how localization strings are provided.

It is possible to define localization keys at runtime but it doesn't feel right:
image
image

**Comment by SirFrostingham** [comment]
Is this feature work going to be added the project? I'm just curious. I think the theme matches the epic loot theme, making combat so much more exciting. I can't wait to get some life steal drops. :)

**Comment by RandyKnapp** [comment]
Yes, I am planning on adding it! I am dealing with a major bug with the
Augmenter code, so once that's resolved I'll get this in the next release.

**Comment by RandyKnapp** [comment]
So I've got this integrated, and it feels SUPER low. Like, with a bronze sword, you're getting like +0.2 health per attack. And even when attacking normally against a hard enemy, that's MUCH slower than just normal food healing. I feel like it should be much stronger or else nobody is going to want to bother with it.

**Comment by SirFrostingham** [comment]
Gotcha. We trust your judgment, since you’re doing the good lord’s work. I did not test it, since I have not built your mod yet (and uh this life steal repo either). I was thinking I may try to build it, but the speed that you develop features for the mod is top notch. Lol. Your mod is easily the best mod for Valheim. They should buy you out, merge your code into the game and have you to join the dev team. :) Though if that happened, they would probably have you work on other projects and I’m sure creativity would be lessened compared to mod work. Thanks for your time!

**Comment by nanonull** [comment]
One of my testing results were: in swamps player with legendary Lifesteal Iron sword can life-steal **50 HP in 16 seconds** in ideal conditions. In comparison minor health potion restores **50 health over 10 seconds**. It is easier to balance up effect from this point. I was afraid to not break health potions by this effect. Maybe effect should heal more than minor health potion at least?

**Comment by SirFrostingham** [comment]
Lifesteal is a tight rope walk. Too much of it and you're a god that nothing can kill (nulling out the need for health potions); too little lifesteal effect and it's so insignificant, players don't use the feature. In my non-professional / gamer-y level opinion, I would say the lifesteal effect should be maybe slightly less than a minor health potion at best. Any more and as you say, you risk breaking the need for health potions. Then again rhetorically, what's the likelihood of getting a lifesteal _sword_ drop and a legendary level item at that? There are 3 factors there. Many prefer the sword only and would not take lifesteal effect on other weapons, unless to test it out for a bit... It's probably going to feel life winning the lotto to get a sword in any metal type object with lifesteal effect? Maybe I am pushing it a little here with guessing at these sorts of feelings, but I'm also guessing I am fairly close.

**Pull request merged**
